name: newGetxCLI
description: A new Flutter project.

publish_to: "none"

version: 0.0.1+2

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  intl: ^0.18.1
  logger:
  flutter_screenutil: ^5.9.0
  crossplat_objectid: ^3.0.0
  dio: ^5.3.3
  lottie: ^2.7.0
  cupertino_icons: ^1.0.2
  connectivity_wrapper: ^1.1.3
  package_info_plus: ^4.2.0
  shared_preferences: ^2.3.2
  fluttertoast: ^8.2.2
  flutter_spinkit: ^5.2.0
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.10+1
  flutter_easyrefresh: ^2.2.1
  permission_handler: ^12.0.0+1
  geolocator: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon" #flutter pub run flutter_launcher_icons
  ios: true
  image_path: "asset/logo/logo.png"
flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/logo/
    - asset/fonts/


  fonts:
    - family: Inter-Black
      fonts:
        - asset: asset/fonts/Inter-Black.ttf
    - family: Inter-Bold
      fonts:
        - asset: asset/fonts/Inter-Bold.ttf
    - family: Inter-Regular
      fonts:
        - asset: asset/fonts/Inter-Regular.ttf
    - family: Inter-Medium
      fonts:
        - asset: asset/fonts/Inter-Medium.ttf
    - family: Inter-SemiBold
      fonts:
        - asset: asset/fonts/Inter-SemiBold.ttf
    - family: norms
      fonts:
        - asset: asset/fonts/norms-Regular.otf
    - family: norms-bold
      fonts:
        - asset: asset/fonts/TTNorms-Bold.otf
    - family: GoogleSans-Regular
      fonts:
        - asset: asset/fonts/GoogleSans-Regular.ttf

        

        
